-- Esquema inicial do OpenBag (versão 0.3.0).
--
-- Gerado pelo Hibernate a partir das entidades, no lugar do antigo ddl-auto=update. Os nomes das chaves
-- estrangeiras e dos únicos (FK..., UK...) e dos checks dos enums (<tabela>_<coluna>_check) são os mesmos
-- que o Hibernate criava, então bancos que já existiam entram com baseline nesta versão sem diferença de nomes.
--
-- A partir daqui, toda mudança no esquema é uma nova migração (V2, V3...). Valor novo num enum também:
-- o check da coluna precisa ser recriado.

-- delivery_routes.street_path é do tipo geometry
CREATE EXTENSION IF NOT EXISTS postgis;

    create table addresses (
        is_default boolean,
        latitude float(53),
        longitude float(53),
        id bigint generated by default as identity,
        user_id bigint,
        number varchar(10) not null,
        zip_code varchar(10) not null,
        state varchar(50) not null,
        city varchar(100) not null,
        complement varchar(100),
        neighborhood varchar(100) not null,
        street varchar(200) not null,
        primary key (id)
    );

    create table association_addon_plans (
        active boolean not null,
        amount numeric(10,2) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        organization_id bigint not null,
        updated_at timestamp(6),
        pricing varchar(20) not null check (pricing in ('PERCENT_OF_FEE','FIXED')),
        name varchar(80) not null,
        description varchar(500),
        primary key (id)
    );

    create table association_benefits (
        active boolean not null,
        valid_until date,
        created_at timestamp(6),
        id bigint generated by default as identity,
        organization_id bigint not null,
        updated_at timestamp(6),
        category varchar(20) not null check (category in ('WORKSHOP','LANGUAGES','EDUCATION','HEALTH','FUEL','PARTS','FOOD','OTHER')),
        phone varchar(20),
        headline varchar(120) not null,
        partner_name varchar(120) not null,
        address varchar(250),
        link varchar(300),
        description varchar(1000),
        logo_url varchar(255),
        primary key (id)
    );

    create table association_documents (
        document_date date,
        created_at timestamp(6),
        file_size bigint not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        uploaded_by_id bigint,
        type varchar(20) not null check (type in ('MINUTES','BYLAWS','FINANCIAL_REPORT','OTHER')),
        title varchar(150) not null,
        file_name varchar(200) not null,
        description varchar(1000),
        file_path varchar(255) not null,
        primary key (id)
    );

    create table association_invites (
        active boolean not null,
        max_uses integer,
        uses_count integer not null,
        created_at timestamp(6),
        created_by_id bigint,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        organization_id bigint not null,
        code varchar(12) not null,
        primary key (id)
    );

    create table association_memberships (
        member_number integer,
        solidarity_contribution numeric(10,2),
        created_at timestamp(6),
        decided_at timestamp(6),
        decided_by_id bigint,
        delivery_person_id bigint not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        invite_id bigint,
        organization_id bigint not null,
        requested_at timestamp(6) not null,
        updated_at timestamp(6),
        origin varchar(20) not null check (origin in ('SELF_REQUEST','MANAGER_CREATED','INVITE')),
        status varchar(20) not null check (status in ('PENDING','ACTIVE','SUSPENDED','REJECTED','LEFT','REMOVED')),
        reason varchar(500),
        primary key (id),
        constraint uk_membership_org_member_number unique (organization_id, member_number)
    );

    create table association_poll_options (
        position integer not null,
        id bigint generated by default as identity,
        poll_id bigint not null,
        label varchar(150) not null,
        primary key (id)
    );

    create table association_poll_votes (
        id bigint generated by default as identity,
        membership_id bigint not null,
        option_id bigint not null,
        poll_id bigint not null,
        voted_at timestamp(6),
        primary key (id),
        constraint uk_poll_votes_poll_membership unique (poll_id, membership_id)
    );

    create table association_polls (
        closed_at timestamp(6),
        closes_at timestamp(6),
        created_at timestamp(6),
        created_by_id bigint,
        id bigint generated by default as identity,
        opened_at timestamp(6),
        organization_id bigint not null,
        status varchar(20) not null check (status in ('DRAFT','OPEN','CLOSED')),
        question varchar(200) not null,
        description varchar(1000),
        primary key (id)
    );

    create table categories (
        is_active boolean,
        id bigint generated by default as identity,
        name varchar(100) not null,
        description varchar(500),
        icon_url varchar(255),
        primary key (id)
    );

    create table combo_items (
        quantity integer not null check (quantity>=1),
        unit_price_snapshot numeric(10,2),
        combo_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id)
    );

    create table combos (
        is_active boolean,
        is_available boolean,
        position integer,
        price numeric(10,2) not null,
        category_id bigint,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        menu_section_id bigint,
        restaurant_id bigint not null,
        updated_at timestamp(6),
        name varchar(200) not null,
        image_url varchar(500),
        description varchar(1000),
        primary key (id)
    );

    create table courier_settlements (
        balance numeric(10,2) not null,
        cash_collected numeric(10,2) not null,
        courier_earnings numeric(10,2) not null,
        orders_count integer not null,
        delivery_person_id bigint,
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        settled_at timestamp(6) not null,
        settled_by bigint,
        staff_courier_id bigint,
        primary key (id)
    );

    create table courier_shifts (
        deliveries_count integer not null,
        start_latitude float(53),
        start_longitude float(53),
        delivery_person_id bigint not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        last_delivery_at timestamp(6),
        restaurant_id bigint,
        started_at timestamp(6) not null,
        vehicle_id bigint,
        mode varchar(10) not null check (mode in ('FREE','FIXED')),
        primary key (id)
    );

    create table customization_groups (
        is_required boolean,
        max_selections integer,
        min_selections integer,
        position integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        name varchar(100) not null,
        primary key (id)
    );

    create table customization_options (
        display_order integer,
        is_available boolean,
        price_modifier numeric(10,2) not null,
        customization_group_id bigint not null,
        id bigint generated by default as identity,
        name varchar(100) not null,
        primary key (id)
    );

    create table delivery_offers (
        courier_fee numeric(10,2) not null,
        delivery_distance_km float(53),
        pickup_distance_km float(53),
        score float(53),
        delivery_person_id bigint not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        offered_at timestamp(6) not null,
        order_id bigint not null,
        responded_at timestamp(6),
        route_id bigint,
        status varchar(20) not null check (status in ('PENDING','ACCEPTED','DECLINED','EXPIRED','CANCELLED')),
        primary key (id)
    );

    create table delivery_person_social_links (
        position integer not null,
        delivery_person_id bigint not null,
        platform varchar(20) not null check (platform in ('INSTAGRAM','FACEBOOK','TIKTOK','WHATSAPP','YOUTUBE','WEBSITE','OTHER')),
        url varchar(255) not null,
        primary key (delivery_person_id, position)
    );

    create table delivery_persons (
        is_active boolean,
        is_available boolean,
        last_latitude float(53),
        last_longitude float(53),
        rating numeric(3,2),
        show_work_history boolean,
        total_deliveries integer,
        total_reviews integer,
        active_vehicle_id bigint,
        created_at timestamp(6),
        current_shift_id bigint,
        id bigint generated by default as identity,
        last_seen_at timestamp(6),
        organization_id bigint,
        updated_at timestamp(6),
        user_id bigint,
        work_status varchar(10) check (work_status in ('OFFLINE','ONLINE','BUSY')),
        document_number varchar(20) not null,
        driver_license varchar(20) not null,
        vehicle_plate varchar(20),
        vehicle_color varchar(30),
        vehicle_model varchar(50),
        slug varchar(80),
        bio varchar(500),
        photo_url varchar(255),
        vehicle_type varchar(255) check (vehicle_type in ('BICYCLE','MOTORCYCLE','CAR','FOOT')),
        primary key (id)
    );

    create table delivery_routes (
        saved_distance_km float(53),
        total_distance_km float(53),
        completed_at timestamp(6),
        created_at timestamp(6),
        delivery_person_id bigint,
        dispatch_at timestamp(6),
        dispatched_at timestamp(6),
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        staff_courier_id bigint,
        origin varchar(10) not null check (origin in ('AUTO','MANUAL')),
        status varchar(20) not null check (status in ('PLANNED','DISPATCHING','ASSIGNED','IN_PROGRESS','DONE','CANCELLED')),
        wait_reason varchar(200),
        street_path_key text,
        street_path geometry(LineString,4326),
        primary key (id)
    );

    create table global_products (
        is_active boolean,
        category_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        barcode varchar(50) not null,
        brand varchar(100),
        name varchar(200) not null,
        description varchar(1000),
        default_image_url varchar(255),
        primary key (id)
    );

    create table layout_configs (
        brand_color varchar(7),
        primary_color varchar(7) not null,
        secondary_color varchar(7) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        updated_at timestamp(6),
        theme_preset varchar(20) check (theme_preset in ('FRESH_GREEN','SUNSET_ORANGE','BERRY_PINK','OCEAN_BLUE','GRAPE_PURPLE','MIDNIGHT_GREEN','MIDNIGHT_BLUE','GRAPHITE')),
        slogan varchar(80),
        primary key (id)
    );

    create table ledger_entries (
        amount numeric(12,2) not null,
        entry_date date not null,
        direction varchar(5) not null check (direction in ('IN','OUT')),
        created_at timestamp(6),
        created_by_id bigint,
        id bigint generated by default as identity,
        invoice_id bigint,
        membership_id bigint,
        organization_id bigint not null,
        account varchar(20) not null check (account in ('GENERAL','SOLIDARITY_FUND')),
        category varchar(20) not null check (category in ('MEMBERSHIP_FEE','ADDON','CONTRIBUTION','AID','EXPENSE','OTHER')),
        description varchar(200) not null,
        primary key (id)
    );

    create table member_addons (
        cancelled_at timestamp(6),
        decided_at timestamp(6),
        id bigint generated by default as identity,
        membership_id bigint not null,
        plan_id bigint not null,
        proposed_at timestamp(6),
        status varchar(20) not null check (status in ('PROPOSED','ACTIVE','DECLINED','CANCELLED')),
        primary key (id)
    );

    create table member_invoice_lines (
        amount numeric(10,2) not null,
        id bigint generated by default as identity,
        invoice_id bigint not null,
        type varchar(20) not null check (type in ('FEE','ADDON','SOLIDARITY')),
        description varchar(120) not null,
        primary key (id)
    );

    create table member_invoices (
        deliveries integer not null,
        due_date date not null,
        earnings numeric(10,2) not null,
        paid_on date,
        reference_month date not null,
        total numeric(10,2) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        membership_id bigint not null,
        organization_id bigint not null,
        registered_by_id bigint,
        payment_method varchar(20) check (payment_method in ('PIX','CASH','TRANSFER','OTHER')),
        status varchar(20) not null check (status in ('OPEN','PAID','WAIVED')),
        notes varchar(500),
        primary key (id),
        constraint uk_member_invoices_membership_month unique (membership_id, reference_month)
    );

    create table menu_sections (
        active boolean not null,
        position integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        updated_at timestamp(6),
        icon varchar(30),
        name varchar(80) not null,
        description varchar(300),
        primary key (id)
    );

    create table opening_hours (
        close_time time(6) not null,
        open_time time(6) not null,
        weekday integer not null check ((weekday<=7) and (weekday>=1)),
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        label varchar(50),
        observation varchar(255),
        primary key (id)
    );

    create table order_item_customizations (
        price_at_purchase numeric(10,2) not null,
        customization_option_id bigint not null,
        id bigint generated by default as identity,
        order_item_id bigint not null,
        group_name varchar(100) not null,
        option_name varchar(100) not null,
        primary key (id)
    );

    create table order_items (
        quantity integer not null,
        subtotal numeric(10,2) not null,
        total_price numeric(10,2) not null,
        unit_price numeric(10,2) not null,
        combo_id bigint,
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        item_name varchar(200),
        observations varchar(500),
        primary key (id)
    );

    create table order_tracking (
        created_at timestamp(6),
        id bigint generated by default as identity,
        order_id bigint,
        timestamp timestamp(6),
        description varchar(500),
        message varchar(500),
        status varchar(255) check (status in ('PENDING','CONFIRMED','PREPARING','READY_FOR_PICKUP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
        primary key (id)
    );

    create table orders (
        change_for numeric(10,2),
        courier_fee numeric(10,2),
        daily_number integer,
        delivery_distance_km float(53),
        delivery_fee numeric(10,2) not null,
        delivery_latitude float(53),
        delivery_longitude float(53),
        estimated_delivery_time integer,
        restaurant_delivery_subsidy numeric(10,2),
        route_sequence integer,
        solo_dispatch boolean,
        subtotal numeric(10,2) not null,
        total_amount numeric(10,2) not null,
        accept_deadline timestamp(6),
        accepted_at timestamp(6),
        assigned_at timestamp(6),
        cancelled_at timestamp(6),
        courier_organization_id bigint,
        courier_settled_at timestamp(6),
        created_at timestamp(6),
        delivered_at timestamp(6),
        delivery_person_id bigint,
        dispatch_released_at timestamp(6),
        dispatched_at timestamp(6),
        expected_ready_at timestamp(6),
        id bigint generated by default as identity,
        order_date timestamp(6) not null,
        picked_up_at timestamp(6),
        ready_at timestamp(6),
        restaurant_id bigint,
        route_id bigint,
        searching_courier_since timestamp(6),
        settlement_id bigint,
        staff_courier_id bigint,
        updated_at timestamp(6),
        user_id bigint,
        display_code varchar(10),
        cancelled_by varchar(12) check (cancelled_by in ('CUSTOMER','RESTAURANT','SYSTEM')),
        channel varchar(12) check (channel in ('APP','COUNTER','PHONE','WHATSAPP')),
        fulfillment varchar(12) check (fulfillment in ('DELIVERY','PICKUP')),
        customer_phone varchar(20),
        customer_name varchar(100),
        delivery_neighborhood varchar(100),
        cancellation_reason varchar(500),
        delivery_address varchar(500),
        order_notes varchar(500),
        order_number varchar(255),
        payment_method varchar(255) check (payment_method in ('CREDIT_CARD','DEBIT_CARD','PIX','CASH','FOOD_VOUCHER')),
        payment_status varchar(255) check (payment_status in ('PENDING','PROCESSING','PAID','FAILED','REFUNDED')),
        status varchar(255) check (status in ('PENDING','CONFIRMED','PREPARING','READY_FOR_PICKUP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
        primary key (id)
    );

    create table organizations (
        fee_due_day integer,
        fee_fixed_amount numeric(10,2),
        fee_monthly_cap numeric(10,2),
        fee_percentage numeric(5,2),
        is_active boolean,
        rate_base_distance_km numeric(5,2),
        rate_base_fee numeric(10,2),
        rate_extra_per_km numeric(10,2),
        address_id bigint,
        admin_user_id bigint,
        approved_at timestamp(6),
        approved_by_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        phone_number varchar(15),
        cnpj varchar(18) not null,
        fee_mode varchar(20) check (fee_mode in ('FIXED','PERCENTAGE')),
        status varchar(20) check (status in ('PENDING_APPROVAL','ACTIVE','REJECTED','SUSPENDED')),
        type varchar(20) check (type in ('ASSOCIATION','COOPERATIVE')),
        company_name varchar(100) not null,
        contact_email varchar(100),
        trading_name varchar(100) not null,
        description varchar(500),
        rejection_reason varchar(500),
        logo_url varchar(255),
        primary key (id)
    );

    create table permissions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        category varchar(50) not null,
        name varchar(100) not null,
        description varchar(255),
        primary key (id)
    );

    create table products (
        is_active boolean,
        is_available boolean,
        position integer,
        preparation_time integer,
        price numeric(10,2) not null,
        promotional_price numeric(10,2),
        category_id bigint,
        created_at timestamp(6),
        deleted_at timestamp(6),
        global_product_id bigint,
        id bigint generated by default as identity,
        menu_section_id bigint,
        restaurant_id bigint,
        updated_at timestamp(6),
        product_type varchar(20) check (product_type in ('GLOBAL_LINKED','CUSTOM')),
        badges varchar(60),
        name varchar(100) not null,
        description varchar(500),
        image_url varchar(255),
        primary key (id)
    );

    create table restaurant_categories (
        category_id bigint not null,
        restaurant_id bigint not null
    );

    create table restaurant_courier_links (
        created_at timestamp(6),
        decided_at timestamp(6),
        delivery_person_id bigint not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        requested_by varchar(20) not null check (requested_by in ('COURIER','RESTAURANT')),
        status varchar(20) not null check (status in ('PENDING','ACTIVE','REJECTED','ENDED')),
        primary key (id)
    );

    create table restaurant_partnerships (
        agreed_base_distance_km numeric(5,2),
        agreed_base_fee numeric(10,2),
        agreed_extra_per_km numeric(10,2),
        proposed_base_distance_km numeric(5,2),
        proposed_base_fee numeric(10,2),
        proposed_extra_per_km numeric(10,2),
        rate_proposal_to_default boolean,
        agreed_at timestamp(6),
        created_at timestamp(6),
        decided_at timestamp(6),
        ended_at timestamp(6),
        id bigint generated by default as identity,
        organization_id bigint not null,
        rate_proposed_at timestamp(6),
        restaurant_id bigint not null,
        ended_by varchar(20) check (ended_by in ('RESTAURANT','ASSOCIATION')),
        rate_proposed_by varchar(20) check (rate_proposed_by in ('RESTAURANT','ASSOCIATION')),
        requested_by varchar(20) check (requested_by in ('RESTAURANT','ASSOCIATION')),
        status varchar(20) check (status in ('PENDING','ACTIVE','DECLINED','ENDED')),
        primary key (id)
    );

    create table restaurants (
        acceptance_timeout_minutes integer,
        auto_print_ticket boolean,
        courier_no_show_minutes integer,
        covers_delivery_difference boolean,
        default_preparation_minutes integer,
        delivery_fee numeric(10,2) not null,
        delivery_time_max integer not null,
        delivery_time_min integer not null,
        fallback_to_open boolean,
        is_active boolean,
        is_open boolean,
        latitude numeric(10,7),
        longitude numeric(10,7),
        minimum_order numeric(10,2) not null,
        price_range varchar(4),
        rating numeric(3,2),
        route_batching_enabled boolean,
        route_dispatch_lead_minutes integer,
        route_max_hold_minutes integer,
        route_max_orders integer,
        total_reviews integer,
        address_id bigint,
        covers_delivery_difference_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        organization_id bigint,
        owner_id bigint,
        partners_ended_notice_at timestamp(6),
        paused_until timestamp(6),
        updated_at timestamp(6),
        acceptance_mode varchar(10) check (acceptance_mode in ('MANUAL','AUTO')),
        phone_number varchar(15) not null,
        cnpj varchar(18) not null,
        courier_policy varchar(20) check (courier_policy in ('OPEN','PARTNERS_ONLY','FIXED_ONLY')),
        delivery_fee_mode varchar(20) check (delivery_fee_mode in ('ASSUME','PASS_THROUGH')),
        name varchar(100) not null,
        slug varchar(100) not null,
        description varchar(500),
        banner_url varchar(255),
        logo_url varchar(255),
        primary key (id)
    );

    create table reviews (
        courier_rating integer,
        restaurant_rating integer not null,
        created_at timestamp(6) not null,
        delivery_person_id bigint,
        id bigint generated by default as identity,
        order_id bigint not null,
        replied_at timestamp(6),
        restaurant_id bigint not null,
        user_id bigint not null,
        courier_comment varchar(500),
        restaurant_comment varchar(500),
        restaurant_reply varchar(500),
        primary key (id)
    );

    create table role_permissions (
        permission_id bigint not null,
        role_id bigint not null,
        primary key (role_id, permission_id)
    );

    create table roles (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        name varchar(50) not null,
        description varchar(255),
        primary key (id)
    );

    create table staff_couriers (
        active boolean not null,
        fee_per_delivery numeric(10,2),
        created_at timestamp(6),
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        phone varchar(20),
        name varchar(100) not null,
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id bigint not null,
        primary key (user_id, role_id)
    );

    create table users (
        is_active boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        phone_number varchar(15) not null,
        email varchar(100) not null,
        full_name varchar(100) not null,
        password varchar(100) not null,
        profile_image_url varchar(255),
        user_type varchar(255) check (user_type in ('CUSTOMER','RESTAURANT_OWNER','DELIVERY_PERSON','ADMIN','ORGANIZATION')),
        primary key (id)
    );

    create table vehicles (
        archived boolean not null,
        created_at timestamp(6),
        delivery_person_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        plate varchar(20),
        type varchar(20) not null check (type in ('BICYCLE','MOTORCYCLE','CAR','FOOT')),
        color varchar(30),
        model varchar(50),
        photo_url varchar(255),
        primary key (id)
    );

    create index idx_addon_plans_organization 
       on association_addon_plans (organization_id);

    create index idx_benefits_organization 
       on association_benefits (organization_id);

    create index idx_documents_organization 
       on association_documents (organization_id);

    create index idx_membership_org_status 
       on association_memberships (organization_id, status);

    create index idx_membership_delivery_person 
       on association_memberships (delivery_person_id);

    create index idx_polls_organization 
       on association_polls (organization_id);

    create index idx_settlement_restaurant 
       on courier_settlements (restaurant_id, settled_at);

    create index idx_shift_courier 
       on courier_shifts (delivery_person_id);

    create index idx_shift_restaurant_open 
       on courier_shifts (restaurant_id, ended_at);

    create index idx_offer_order 
       on delivery_offers (order_id);

    create index idx_offer_courier_status 
       on delivery_offers (delivery_person_id, status);

    create index idx_offer_status_expires 
       on delivery_offers (status, expires_at);

    create index idx_route_restaurant_status 
       on delivery_routes (restaurant_id, status);

    create index idx_ledger_organization_date 
       on ledger_entries (organization_id, entry_date);

    create index idx_member_addons_membership 
       on member_addons (membership_id);

    create index idx_member_invoices_organization_month 
       on member_invoices (organization_id, reference_month);

    create index idx_menu_section_restaurant 
       on menu_sections (restaurant_id, position);

    create index idx_courier_link_restaurant 
       on restaurant_courier_links (restaurant_id);

    create index idx_courier_link_courier 
       on restaurant_courier_links (delivery_person_id);

    create index idx_partnership_restaurant 
       on restaurant_partnerships (restaurant_id);

    create index idx_partnership_organization 
       on restaurant_partnerships (organization_id);

    create index idx_review_restaurant 
       on reviews (restaurant_id, created_at);

    create index idx_review_courier 
       on reviews (delivery_person_id);

    create index idx_staff_courier_restaurant 
       on staff_couriers (restaurant_id);

    create index idx_vehicles_delivery_person 
       on vehicles (delivery_person_id);

    alter table if exists association_invites 
       add constraint ukg5nj7odet0ec657pw8u6tsryd unique (code);

    alter table if exists delivery_persons 
       add constraint ukeqopk21gq61rkfso6p23il8r unique (user_id);

    alter table if exists delivery_persons 
       add constraint uki4ti8xxk6k9oqss8t1d8831fk unique (document_number);

    alter table if exists delivery_persons 
       add constraint ukpeqa1skkwdeud3tjsesoa6e92 unique (driver_license);

    alter table if exists delivery_persons 
       add constraint uk7icux93p4itnnkb8oxph0jqa4 unique (slug);

    alter table if exists global_products 
       add constraint ukt5jae86cb65x8hdopco3yvlsn unique (barcode);

    alter table if exists layout_configs 
       add constraint uk89g9cby2tdrdwk0bcngthy45a unique (restaurant_id);

    alter table if exists orders 
       add constraint uknthkiu7pgmnqnu86i2jyoe2v7 unique (order_number);

    alter table if exists organizations 
       add constraint uk8wjtwx7nw268x0ljdywku2o33 unique (address_id);

    alter table if exists organizations 
       add constraint ukt8uae1qx4ccn3fsffm2236rl8 unique (cnpj);

    alter table if exists permissions 
       add constraint ukpnvtwliis6p05pn6i3ndjrqt2 unique (name);

    alter table if exists restaurants 
       add constraint ukqmof4bn52u3t3qtpqlt80ypej unique (address_id);

    alter table if exists restaurants 
       add constraint uknhdlexkkkbfuy7xv45eb1ubx8 unique (cnpj);

    alter table if exists restaurants 
       add constraint ukbqfy5owwx6allqo3q7sfjk1il unique (slug);

    alter table if exists reviews 
       add constraint uksbkc1fll14ly5y6yxxk2jwlef unique (order_id);

    alter table if exists roles 
       add constraint ukofx66keruapi6vyqpv6f2or37 unique (name);

    alter table if exists users 
       add constraint uk6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists addresses 
       add constraint FK1fa36y2oqhao3wgg2rw1pi459 
       foreign key (user_id) 
       references users;

    alter table if exists association_addon_plans 
       add constraint FK6nsfae0lmis5rg0m56y5b5yun 
       foreign key (organization_id) 
       references organizations;

    alter table if exists association_benefits 
       add constraint FKkw1rull98hroscuguj93bhw6p 
       foreign key (organization_id) 
       references organizations;

    alter table if exists association_documents 
       add constraint FKlxl5ccua2w1u5fdjnxau1bl01 
       foreign key (organization_id) 
       references organizations;

    alter table if exists association_documents 
       add constraint FK3p7tiqokjam9q25ovcmiia7tq 
       foreign key (uploaded_by_id) 
       references users;

    alter table if exists association_invites 
       add constraint FKp6axlclmdqoxt874yrm5r8ilc 
       foreign key (created_by_id) 
       references users;

    alter table if exists association_invites 
       add constraint FK3f7wtlh0kycv7remq3rq0hopr 
       foreign key (organization_id) 
       references organizations;

    alter table if exists association_memberships 
       add constraint FKeets37kg8cm0kseb98u41io4l 
       foreign key (decided_by_id) 
       references users;

    alter table if exists association_memberships 
       add constraint FKo6q2q85xk4dsoax8j95eu7ri 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists association_memberships 
       add constraint FKcdeea36r1ytyrdadrb1np386w 
       foreign key (invite_id) 
       references association_invites;

    alter table if exists association_memberships 
       add constraint FKd071dlcsva1uallc4js521yhu 
       foreign key (organization_id) 
       references organizations;

    alter table if exists association_poll_options 
       add constraint FKl05bg8ksnrg678ivo21dtuwl 
       foreign key (poll_id) 
       references association_polls;

    alter table if exists association_poll_votes 
       add constraint FKne7cq06f9gtsibebsskcun0sr 
       foreign key (membership_id) 
       references association_memberships;

    alter table if exists association_poll_votes 
       add constraint FKs42eu3u6l8w7h3k95f7edbcyh 
       foreign key (option_id) 
       references association_poll_options;

    alter table if exists association_poll_votes 
       add constraint FKtoeus2iif1bgebjbfg508p8ul 
       foreign key (poll_id) 
       references association_polls;

    alter table if exists association_polls 
       add constraint FKlxhxgj8sudu2cput5ai4l6gm 
       foreign key (created_by_id) 
       references users;

    alter table if exists association_polls 
       add constraint FKd87qvpkulvafp29pkfm8089fh 
       foreign key (organization_id) 
       references organizations;

    alter table if exists combo_items 
       add constraint FK48h944x1aynyjkgfxa1tu5n32 
       foreign key (combo_id) 
       references combos;

    alter table if exists combo_items 
       add constraint FKp7wjg7ht16w8bfu0623pcwqp0 
       foreign key (product_id) 
       references products;

    alter table if exists combos 
       add constraint FK4m0595edme3t6cwabbgebcpvn 
       foreign key (category_id) 
       references categories;

    alter table if exists combos 
       add constraint FKn67x1gn9schese7rfvx37470p 
       foreign key (menu_section_id) 
       references menu_sections;

    alter table if exists combos 
       add constraint FKmu3f4bn8weg03vehxfw2mdc40 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists courier_settlements 
       add constraint FKn9xlg259nc5igxpilv992fjrb 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists courier_settlements 
       add constraint FKsj78vj8j2ahw662livrfkask0 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists courier_settlements 
       add constraint FKqupqhass3l81up93qtipdvop8 
       foreign key (settled_by) 
       references users;

    alter table if exists courier_settlements 
       add constraint FK1kwq9xo95qtd8nbma3gistp8s 
       foreign key (staff_courier_id) 
       references staff_couriers;

    alter table if exists courier_shifts 
       add constraint FK7mkdqupbnx8qcxnggt038n8sk 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists courier_shifts 
       add constraint FK16dfscglx89mdoqe7p5ywtvsc 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists courier_shifts 
       add constraint FKul75vcx41fpc25vh2d455w0x 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists customization_groups 
       add constraint FKjpvc2wc2o6gphvw7f1o0yeq8y 
       foreign key (product_id) 
       references products;

    alter table if exists customization_options 
       add constraint FKj5y6c08bf5otei7w2ksuyb857 
       foreign key (customization_group_id) 
       references customization_groups;

    alter table if exists delivery_offers 
       add constraint FK5r5npuspm4uge6orcshad3lsl 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists delivery_offers 
       add constraint FKhkfokl3oop7udruffst9t9int 
       foreign key (order_id) 
       references orders;

    alter table if exists delivery_offers 
       add constraint FK9k2wsa2oo50ck1ixjl4bdjk49 
       foreign key (route_id) 
       references delivery_routes;

    alter table if exists delivery_person_social_links 
       add constraint FKl9i9tctl5nfprud9pvo7p7wav 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists delivery_persons 
       add constraint FKrcbj3bm3j3mem1rou2xa59mv7 
       foreign key (active_vehicle_id) 
       references vehicles;

    alter table if exists delivery_persons 
       add constraint FK40mbxuv2rdrjlrm1peiglgml9 
       foreign key (current_shift_id) 
       references courier_shifts;

    alter table if exists delivery_persons 
       add constraint FKtrn2ndmup5v746quq8lpkjsg0 
       foreign key (organization_id) 
       references organizations;

    alter table if exists delivery_persons 
       add constraint FKfrxt1p46rlcff256odj9gm287 
       foreign key (user_id) 
       references users;

    alter table if exists delivery_routes 
       add constraint FK4ox28dbof31m7vo3s63jtmlei 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists delivery_routes 
       add constraint FKc3bgpvo3xy92b9ljn8o8qvlwi 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists delivery_routes 
       add constraint FKd9qg0itg7q8kh5l3qsiwscu3a 
       foreign key (staff_courier_id) 
       references staff_couriers;

    alter table if exists global_products 
       add constraint FKpcuukr2suh09fucvr4v93x4xa 
       foreign key (category_id) 
       references categories;

    alter table if exists layout_configs 
       add constraint FK6vqx7nwwuqnag0wcyge9wakea 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists ledger_entries 
       add constraint FKlxnepu6k8gqoe1kudvfq9wp84 
       foreign key (created_by_id) 
       references users;

    alter table if exists ledger_entries 
       add constraint FKrqu87pg30ad2mv4owf4mfsq50 
       foreign key (invoice_id) 
       references member_invoices;

    alter table if exists ledger_entries 
       add constraint FKk45p7jkro0hcdiglefi6gcqgt 
       foreign key (membership_id) 
       references association_memberships;

    alter table if exists ledger_entries 
       add constraint FKjxdhi9m1fu4vhmjmg6e5n2vh4 
       foreign key (organization_id) 
       references organizations;

    alter table if exists member_addons 
       add constraint FKg02fm8hcluhv7nm84i1y6b56o 
       foreign key (membership_id) 
       references association_memberships;

    alter table if exists member_addons 
       add constraint FKdqbw0dg39d14j8mif73pgwxe8 
       foreign key (plan_id) 
       references association_addon_plans;

    alter table if exists member_invoice_lines 
       add constraint FKd8xkoungnc78omhw40ajj0f8g 
       foreign key (invoice_id) 
       references member_invoices;

    alter table if exists member_invoices 
       add constraint FKfy73wu0emi1r84s4g7o1sf2up 
       foreign key (membership_id) 
       references association_memberships;

    alter table if exists member_invoices 
       add constraint FKb4s4jy8on4nsenagmqxb7s1qn 
       foreign key (organization_id) 
       references organizations;

    alter table if exists member_invoices 
       add constraint FK68p3ncosohur9ib1ik3c4tdvc 
       foreign key (registered_by_id) 
       references users;

    alter table if exists menu_sections 
       add constraint FK50gew5xea3assxcvmlwuoicx4 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists opening_hours 
       add constraint FK5dgcr0nmedj2g2ru4lqdld48n 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists order_item_customizations 
       add constraint FKn2a5mi1et9vfvopgwtk7bxb2k 
       foreign key (customization_option_id) 
       references customization_options;

    alter table if exists order_item_customizations 
       add constraint FK9icomx5dcq92o8u99l1te7bql 
       foreign key (order_item_id) 
       references order_items;

    alter table if exists order_items 
       add constraint FK406a8m2k9pylvb0rynoxx4o43 
       foreign key (combo_id) 
       references combos;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists order_tracking 
       add constraint FKeu0lumcx8bcx6lk035xiklty0 
       foreign key (order_id) 
       references orders;

    alter table if exists orders 
       add constraint FKg3r9gl8t3twi9sdxflrb36g3k 
       foreign key (courier_organization_id) 
       references organizations;

    alter table if exists orders 
       add constraint FKlubga8dmt0t3sqvgmsp3tr7ws 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists orders 
       add constraint FK2m9qulf12xm537bku3jnrrbup 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists orders 
       add constraint FKpu3dn7857gsfr4u2jdx8ug8x7 
       foreign key (route_id) 
       references delivery_routes;

    alter table if exists orders 
       add constraint FKqm5fegsake226bbcf9qs8pq5u 
       foreign key (settlement_id) 
       references courier_settlements;

    alter table if exists orders 
       add constraint FKc2mmnmhuxa13htyerwgt161y1 
       foreign key (staff_courier_id) 
       references staff_couriers;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists organizations 
       add constraint FK2pcjeyffqurfmgrypdta1rnye 
       foreign key (address_id) 
       references addresses;

    alter table if exists organizations 
       add constraint FKhh2ecomgpjlmmed85w92706k4 
       foreign key (admin_user_id) 
       references users;

    alter table if exists organizations 
       add constraint FKhx5ovaihi2evwa6rm1g7yj2gj 
       foreign key (approved_by_id) 
       references users;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists products 
       add constraint FK2yc3dxahxii3j40971d9wtoi3 
       foreign key (global_product_id) 
       references global_products;

    alter table if exists products 
       add constraint FKjoiwi7dmwgohlq1fek2uk4n9c 
       foreign key (menu_section_id) 
       references menu_sections;

    alter table if exists products 
       add constraint FK8tiok83nulb20v1i722tlil3a 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists restaurant_categories 
       add constraint FK4kg1d5bcfdt8fn2qh16ptrnfm 
       foreign key (category_id) 
       references categories;

    alter table if exists restaurant_categories 
       add constraint FKiq9qlrhc1dciym7ai5m4bva27 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists restaurant_courier_links 
       add constraint FKfxlgmko4mxae4f4gunu6lwka7 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists restaurant_courier_links 
       add constraint FKrjf1dvranhvyi5ml7f2tw4s6q 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists restaurant_partnerships 
       add constraint FK7fnrkgn8tku8cpr7w0ap7c6ll 
       foreign key (organization_id) 
       references organizations;

    alter table if exists restaurant_partnerships 
       add constraint FKc61f184arrp3m4m45wpx7y4tw 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists restaurants 
       add constraint FKf77xr396uxbl0crr0pq0qj2q7 
       foreign key (address_id) 
       references addresses;

    alter table if exists restaurants 
       add constraint FK8fqq8fkoc4lma0w3jibesd2m2 
       foreign key (organization_id) 
       references organizations;

    alter table if exists restaurants 
       add constraint FKp5mmmypepihvmkdb83qwugr4d 
       foreign key (owner_id) 
       references users;

    alter table if exists reviews 
       add constraint FKc2xxbhglov0b7qbx8n5mr7w5h 
       foreign key (delivery_person_id) 
       references delivery_persons;

    alter table if exists reviews 
       add constraint FKqwgq1lxgahsxdspnwqfac6sv6 
       foreign key (order_id) 
       references orders;

    alter table if exists reviews 
       add constraint FKsu8ow2q842enesfbqphjrfi5g 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists reviews 
       add constraint FKcgy7qjc1r99dp117y9en6lxye 
       foreign key (user_id) 
       references users;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists staff_couriers 
       add constraint FK2x9nvu23w9r5g5gqud47fwimb 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;

    alter table if exists vehicles 
       add constraint FKr9jp2upnr7e72fwoonaw124db 
       foreign key (delivery_person_id) 
       references delivery_persons;
