-- Idempotência (0.4.0, item 4): a mesma ação enviada de novo com o mesmo cabeçalho Idempotency-Key recebe a
-- resposta da primeira vez, em vez de ser aplicada de novo (ex.: pedido repetido depois de um timeout).

CREATE TABLE idempotency_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    idempotency_key varchar(100) NOT NULL,
    method varchar(10) NOT NULL,
    path varchar(300) NOT NULL,
    request_hash varchar(64) NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    response_status integer,
    response_content_type varchar(100),
    response_body text,
    created_at timestamp NOT NULL DEFAULT now(),
    completed_at timestamp,
    CONSTRAINT uk_idempotency_keys_user_key UNIQUE (user_id, idempotency_key)
);

CREATE INDEX idx_idempotency_keys_created_at ON idempotency_keys (created_at);
