-- Ocorrências ligadas ao pedido (0.5.0, item 1): o entregador relata o que atrapalhou a entrega, a loja vê no
-- pedido e a cooperativa vê a contagem por tipo e por loja. Nunca vira nota nem penalidade do entregador.

CREATE TABLE order_incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders (id),
    restaurant_id bigint NOT NULL REFERENCES restaurants (id),
    organization_id bigint REFERENCES organizations (id),
    delivery_person_id bigint NOT NULL REFERENCES delivery_persons (id),
    type varchar(30) NOT NULL CHECK (type IN ('ORDER_NOT_READY', 'WRONG_ADDRESS', 'CUSTOMER_NOT_FOUND',
        'ORDER_MISMATCH', 'RESTAURANT_CLOSED', 'VEHICLE_PROBLEM', 'ACCESS_PROBLEM', 'OTHER')),
    note varchar(300),
    created_at timestamp(6) NOT NULL
);

CREATE INDEX idx_order_incident_order ON order_incidents (order_id);
CREATE INDEX idx_order_incident_organization ON order_incidents (organization_id, created_at);
