-- Comunicados da cooperativa (0.5.0, item 4): o gestor publica avisos, reuniões, mudanças e parcerias; o cooperado
-- vê na área dele, com os não lidos no resumo.

CREATE TABLE association_announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations (id),
    type varchar(30) NOT NULL CHECK (type IN ('NOTICE', 'MEETING', 'OPERATIONAL_CHANGE', 'RATE_CHANGE',
        'NEW_PARTNERSHIP', 'TRAINING')),
    title varchar(150) NOT NULL,
    body varchar(2000) NOT NULL,
    event_at timestamp(6),
    published_at timestamp(6) NOT NULL,
    archived_at timestamp(6),
    created_by_id bigint REFERENCES users (id),
    CONSTRAINT ck_announcements_meeting_date CHECK (type <> 'MEETING' OR event_at IS NOT NULL)
);

CREATE INDEX idx_announcements_organization ON association_announcements (organization_id, published_at);

CREATE TABLE association_announcement_reads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id bigint NOT NULL REFERENCES association_announcements (id),
    membership_id bigint NOT NULL REFERENCES association_memberships (id),
    read_at timestamp(6) NOT NULL,
    CONSTRAINT uk_announcement_reads UNIQUE (announcement_id, membership_id)
);
